name: Release Deployment Test

on:
  release:
    types: [published]
    
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Deploy
        id: deploy
        run: echo "url=https://xiel.dev" >> $GITHUB_OUTPUT
